---
layout: post
title: Sample prep for physiology - ENCORE Bermuda samples
date: '2025-09-10'
category: [ Physiology ]
tags: [ Coral, Protein, Algae count, Chlorophyll ]
---

#### Preparing Coral Homogenate for Physiological Analyses for the Bermuda ENCORE project

**Protocols used**
- [Airbrushing protocol](https://zdellaert.github.io/ZD_Putnam_Lab_Notebook/Physiology-Airbrushing-Protocol/)

I followed the above protocol to separate the tissue from the skeleton, which will then be used for surface area measurements using the wax-dipping method. The fragments belong to the species _Madracis decactis_ (Mdec), _Diploria labyrinthiformis_ (Dlab), _Montastraea cavernosa_ (Mcav), and _Porites astreoides_ (Past).

I divided the tissue homogenate into aliquots as follows (aliquots were then stored at -80°):

- [Chlorophyll](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/Chlorophyll-Protocol/) - 1.5 ml
- [Symbiont Density](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/GUAVA-Protocol/) - 1.5 ml
- [Protein](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/Total-Protein-Protocol/) - 1.5 ml
- [Lipids](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/Gravimetric-Lipids-Protocol/) - 1.5 ml
- [Carbohydrates](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/Carbohydrates-Protocol/) - 1.5 ml
- [Ashe-free dry weight](https://fscucchia-labnotebooks.github.io/FScucchia_Putnam_Lab_Notebook/Ashe-free-dry-weight-Protocol/) - 5 ml
- Spare - 1 ml at least (if enough tissue)

**Sample list**

Here is the list of samples that were processed:

| Date || Sample name || Temp Cat || Volum of PBS added (ml) |
| 20250715    ||  Past-C3          ||  33        ||     45                    |
| 20250716    ||  Dlab-A3           ||  33        ||     35                    |
| 20250716     ||  Dlab-D3           ||  33        ||      34                   |
| 20250721      || Mcav-D3          ||  33        ||    41                     |
| 20250723      || Mdec-E3           || 33         ||   42.5                      |
| 20250723      || Dlab-B3            || 33         ||     22.5                    |
| 20250723      || Mcav-C7            || 36         ||     38                    |
| 20250730      || Dlab-E7            || 36         ||     35                    |
| 20250730      || Past-A7            ||   36       ||    25                    |
| 20250730      || Mdec-D7            ||   36       ||    15                     |
| 20250730      || Past-B7            ||   36       ||    27.5                     |
| 20250730      || Dlab-C7            ||   36       ||    25                     |
| 20250731      || Mdec-D6            ||   26       ||    26                     |
| 20250731      || Dlab-F6            ||   26       ||    23                     |
| 20250731      || Past-E6            ||   26       ||    16                     |
| 20250731      || Dlab-B6            ||   26       ||    24                     |
| 20250731      || Mcav-A6           ||  26        ||    15                    |
| 20250814      || Mdec-F3           ||  33        ||    40                    |
| 20250814      || Past-F3           ||  33        ||    15                    |
| 20250814      || Mcav-E3           ||  33       ||     50                   |
| 20250814      || Dlab-E3           ||   33      ||     36                   |
| 20250814      || Mcav-C3           ||   33      ||     34.5                   |
| 20250814      || Mdec-D3           ||   33      ||     52                   |
| 20250814      || Past-A3           ||  33      ||      35                  |
| 20250814      || Past-B3           ||   33      ||     40                   |
| 20250814      || Dlab-D4           ||  16       ||     37.5                   |
| 20250814      || Mdec-A3           || 33        ||     47.5                   |
| 20250904      || Mcav-F4           || 16        ||     19                   |
| 20250904      || Dlab-F4       || 16  ||  29      |
| 20250904      || Mdec-D4       ||  16 ||  29      |
| 20250904      || Past-E4       ||16  ||   No Homogenate     |
| 20250904      || Past-F4       || 16 ||   28|